### ISSUE TITLE
canvg officially on git

### ISSUE THREAD

**Issue by gabelerner** [shprink/canvg#1]
will add bower/gulp soon and you should be able to fork from there

https://github.com/gabelerner/canvg

**Comment by shprink** [comment]
Hi,

Feel free to copy my gulpfile to create packaged version of your library. I am going to update my README to link to your repo and set mine as DEPRECATED.

**Comment by morioust** [comment]
Would it be possible to also unregister `shprink/canvg` from the bower registry and register `gabelerner/canvg` as `canvg`?
Currently the [registry lists both](http://bower.io/search/?q=canvg), which might be confusing (I first did a `bower install canvg`).

**Comment by shprink** [comment]
I will do it if I recall my password :P
